config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Web Routes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, format: :json do
          resources :comments, format: :json
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  #  :jwt_authenticatble, jwt_revocation_strategy: JwtDenylist

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name,
            length: { minimum: 3, message: 'fields can not be less than 3 letters' }
  validates :bio,
            length: { minimum: 12, maximum: 500, message: 'fields can not be less than 12 and can not be more than 500 letters' }
  validates_format_of :photo, with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: 'field is not a valid url'
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[admin default].freeze

  def recent_posts
    posts.includes([:author]).last(3)
  end

  def is?(query_role)
    role == query_role.to_s
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
    render json: @users
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.where(id: params[:user_id])
    render json: @user
  end

  # user /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all_users.html.erb
<% @users.each do |user|%>
    <div class="container">
        <div class="image-container">
          <img src=<%= user.photo %> class="img-contained" />
        </div>
        <div class="txt-container">
          <span class="txt-box"><%= link_to user.name, user_path(user) %></span>
          <span class="posts-count">
            Posts Count: <%= user.posts.length %>
          </span>
        </div>
    </div>
  <% end %>

app/views/users/_users_bio.html.erb
<section class="interaction-data">
  <% @user.recent_posts.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id) do %>
      <div class="user-recent-post">
        <p class="post-title"><strong>Post</strong> : <%= post.title %></p>
        <p class="post-text"><%= post.text %></p>
        <div class="comment-info">
      <p class="comment-text">
        Comments: <%= post.comments_counter || 0 %>,<br> Likes: <%= post.likes_counter || 0 %>
      </p>
    </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/index.html.erb
<main>
  <%= render "users/all_users" %>
</main>

app/views/users/show.html.erb
<section class="post-container">
  <div class="container">
    <div class="image-container">
      <img src=<%= @user.photo %> class="img-contained" />
    </div>
    <div class="txt-container">
      <span class="txt-box"><%= @user.name %></span>
      <span class="posts-count">
        Posts Count: <%= @user.posts.length %>
      </span>
    </div>
  </div>
  <p class="user-bio"><%= @user.bio %></p>
      <%= render "users/users_bio" %>
      <div class="btn-container">
        <button class="link-btn">
          <%= link_to "See all posts", user_posts_path(@user), class:"text-button" %>
        </button>
      </div>
    </section>