config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Web Routes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, format: :json do
          resources :comments, format: :json
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter

  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  validates :title,
            length: { minimum: 5, maximum: 250, message: 'fields can not be less than 5 letters and more than 250 letters' }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_five_comments
    @comments = comments.includes([:author]).last(5)
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.where(author_id: params[:user_id])
    render json: @posts
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: { message: 'Post created successfully' }, status: :created
    else
      render json: { message: 'Could not create post' }, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { message: 'Post not found for this user' }, status: :not_found
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.fetch(:post, {})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @post_comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @new_post = Post.new(post_params)
    @new_post.author_id = current_user.id
    @new_post.likes_counter = 0
    @new_post.comments_counter = 0

    if @new_post.save!
      redirect_to user_posts_path(current_user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<section>
  <%= link_to "Create new Post", new_user_post_path(@user) %>
  <div class="container">
    <div class="image-container">
      <img src=<%= @user.photo %> class="img-contained" />
    </div>
    <div class="txt-container">
      <span class="txt-box"><%= @user.name %></span>
      <span class="posts-count">
        Posts Count: <%= @user.posts.length %>
      </span>
    </div>
  </div>
  <div class="user-posts">
    <% @user.posts.includes([:comments]).each do |post| %>
      <div class="post-data">
        <h2 class="post-title"><%= link_to post.title, user_post_path(@user, post) %></h2>
        <p class="text-center">
          <%= post.text %>
        </p>
        <section class="counters">
          Comments: <%= post.comments_counter || 0 %>
          Likes: <%= post.likes_counter || 0 %>
        </section>
        <section class="counters">
          <% post.comments.each do |comment|%>
            <% if comment %>
              <p class="comment-author">
              <%= comment.author.name %>
            </p>
            <p class="comment-author text-center">
              <%= comment.text %>
            </p>
            <% else %>
              <p class="text-center">No comments for this post yet :(</p>
            <% end %>
          <% end %>
        </section>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section class="form-container">
  <%= form_with model: @post, url: user_posts_path, class: "post-form" do |f|%>
    <div class="form-blocks">
      <span class="form-header">Create New Post</span>
    </div>
    <div class="form-blocks">
      <%= f.text_field :title, placeholder: "Post Title", class: "form-input" %>
    </div>
    <div class="form-blocks">
      <%= f.text_field :text, placeholder: "Post Text", class: "form-input" %>
    </div>
    <div class="form-blocks">
      <%= f.submit "submit", class: "primary-btn" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="comment-container">
  <div class="comment-info">
    <div class="comment-title-box">
      <p class="comment-title">Post : <%= @post.title %> by <%= @post.author.name %></p>
    </div>
    <div class="comment-info">
      <p><%= @post.text %></p>
      <p class="comment-text">
        Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %>
      </p>
    </div>
    <%= render "likes/likes_form" %>
    <% if can? :destroy @post%>
      <% button_to 'Delete', user_post_path(@user, @post), method: :delete %>
    <% end %>
  </div>
  <div class="comment-info">
    <section class="comment-form">
        <%= form_with model: Comment, url: user_post_comments_path(@post.author, @post) do |f| %>
          <div class="form-blocks">
            <span class="form-header">Comment on Post</span>
          </div>
          <div class="form-blocks">
            <%= f.text_field :text, placeholder: "Comment text", class: "form-input" %>
          </div>
          <div class="form-blocks">
            <%= f.submit "submit", class: "primary-btn" %>
          </div>
      <% end %>
    </section>
    <section class="comments-section">
      <p class="comment-author">
        <% if @post_comments.length != 0 %>
          <% @post_comments.includes([:author]).each do |comment| %>
            <p class="comment-author">
              <%= comment.author.name %>
            </p>
            <p class="comment-author">
              <%= comment.text %>
            </p>
          <% end %>
        <% else %>
          <span class="empty-comment">No comments added for this post yet :(</span>
        <% end %>
      </p>
    </section>
  </div>
</section>